osx_image: xcode9.1
language: objective-c
xcode_sdk: iphonesimulator11.1
git:
  depth: 1
cache:
- bundler
- cocoapods
before_install:
- brew update
install:
- gem install bundler
- bundle install
- bundle exec pod repo update --silent
- bundle exec pod install
before_script:
- export LANG=en_US.UTF-8
script:
- set -o pipefail && travis_retry xcodebuild -workspace Audiobook.xcworkspace -scheme Audiobook -configuration Debug -destination "id=8303F643-76A3-4369-B02E-CA814E28B305" clean test | xcpretty -f `xcpretty-travis-formatter`
notifications:
  email: false