# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "8541bf08-7936-4c4e-9f56-717b289870f2"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  build_app(
    # scheme: "YourScheme",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    # keys for organization: oleizer
    api_token: "9453b751f4670d73f8d818092e469ec60877c76c",
    build_secret: "54f0227ed4eb5753777bc7fccb16fa03c86b9b2d42a2debd381422c5a143799c"
  )
end